// Generates data/checklist.js from the amazon-product-launch skill's reference files.
// Usage: node scripts/build-data.mjs [path-to-references-folder]
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const refs = resolve(process.argv[2] || join(root, '..', 'amazon-product-launch', 'amazon-product-launch', 'references'));

function parseChecklist(file, market) {
  const items = [];
  let phase = '';
  let section = '';
  const rowRe = new RegExp(`^\\|\\s*(${market}-(?:PRE|POST)-\\d+)\\s*\\|`);
  for (const raw of readFileSync(join(refs, file), 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    const ph = line.match(/^#\s+(PRE-LAUNCH|POST-LAUNCH)\s*$/);
    if (ph) { phase = ph[1] === 'PRE-LAUNCH' ? 'pre' : 'post'; continue; }
    const sec = line.match(/^##\s+([A-D]\d+\..*)$/);
    if (sec) { section = sec[1].trim(); continue; }
    if (!rowRe.test(line)) continue;
    const cells = line.replace(/^\||\|$/g, '').split('|').map(c => c.trim());
    if (cells.length !== 7) throw new Error(`Malformed row in ${file}: ${line}`);
    const [id, when, owner, scope, gate, source, task] = cells;
    items.push({ id, market, phase, section, when, owner, scope, blocking: gate === 'BLOCKING', source, task });
  }
  return items;
}

function parseLessons(file) {
  const lessons = [];
  for (const raw of readFileSync(join(refs, file), 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!/^\|\s*\d+\s*\|/.test(line)) continue;
    const cells = line.replace(/^\||\|$/g, '').split('|').map(c => c.trim());
    if (cells.length !== 5) throw new Error(`Malformed lesson row: ${line}`);
    const [n, what, impact, control, ids] = cells;
    lessons.push({ n: Number(n), what, impact, control, ids: ids.split(',').map(s => s.trim()).filter(Boolean) });
  }
  return lessons;
}

const data = {
  CA: parseChecklist('canada-checklist.md', 'CA'),
  US: parseChecklist('usa-checklist.md', 'US'),
  lessons: parseLessons('lessons-learned.md'),
};

const allIds = new Set([...data.CA, ...data.US].map(i => i.id));
for (const l of data.lessons) {
  for (const id of l.ids) if (!allIds.has(id)) throw new Error(`Lesson #${l.n} references unknown checklist ID ${id}`);
}

mkdirSync(join(root, 'data'), { recursive: true });
writeFileSync(
  join(root, 'data', 'checklist.js'),
  `// Generated by scripts/build-data.mjs from the amazon-product-launch skill. Do not edit by hand.\nwindow.CHECKLIST = ${JSON.stringify(data, null, 1)};\n`,
);
console.log(`CA: ${data.CA.length} items, US: ${data.US.length} items, lessons: ${data.lessons.length}`);
